
- name: copy the config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)


- name: Create - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.82.124:8080
    user: chandra
    password: "{{ jenkins_password }}"






