
- name: Create - folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{ item }}"
    url: http://172.31.82.124:8080
    user: chandra
    password: "{{jenkins_password}}"
  loop: "{{ folder }}"


- name: include the task m-pipeline
  ansible.builtin.include_tasks: m-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"


- name: include the task m-pipeline
  ansible.builtin.include_tasks: s-pipeline.yml
  loop: "{{ S_ci_pipeline_jobs }}"

