- name: Create - folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{ item }}"
    url: http://172.31.80.156:8080
    user: chandra
    password: "{{jenkins_password}}"
  vars:
    component: "{{item.name}}"
    dir: "{{item.dir}}"

  loop: "{{ folder }}"


- name: include the task pipeline
  ansible.builtin.include_tasks: pipeline.yml
  vars:
    component: "{{item.name}}"
    dir: "{{item.dir}}"
  loop: "{{ ci_pipeline_jobs }}"

