- name: copy the config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/job.xml

- name: Create - folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{ item }}"
    url: http://172.31.80.156:8080
    user: chandra
    password: "{{jenkins_password}}"
  loop: "{{ folder }}"


- name: include the task pipeline
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

