
#- name: copy the config file
#  ansible.builtin.template:
#    src: job.xml
#    dest: /tmp/job.xml


- name: Create - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.80.156:8080
    user: chandra
    password: "{{ jenkins_password }}"


